routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::get('/dashboard',function(){
  return view('chat.dashboard');
})->name('dashboard');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Invite Friends
Route::resource('/invite-friends','InviteFriendsController');

//Add Friends
Route::resource('/add-friends','AddFriendsController');
Route::post('/store-request/{id}','AddFriendsController@storeRequest')->name('storeRequest');
Route::get('/request-list','AddFriendsController@requestList')->name('requestList');
Route::post('/request-list/status-update/{id}','AddFriendsController@updateStatus')->name('request.updateStatus');

//chat
Route::resource('/chat','ChatController');
Route::post('/chat/store','ChatController@store');
Route::get('/chat/chat-with-friend/{id}','ChatController@chatWithFriend')->name('chat.chatWithFriend');

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\AddFriend;
use App\Message;
use App\Helper;
use App\User;
class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = AddFriend::where('request_sender',Auth::user()->id)->orwhere('request_receiver',Auth::user()->id)->where('request_status','2')->orderBy('id','desc')->get();
        return view('chat.message.friends-list',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = request('friend_id');
        $addFriend_id = AddFriend::orWhere([['request_sender',Auth::user()->id],['request_receiver',$id]])->orWhere([['request_sender',$id],['request_receiver',Auth::user()->id]])->where('request_status','2')->first()->id;
        $message = new Message();
        $message->add_friends_id = $addFriend_id;
        $message->user_id = Auth::user()->id;
        $message->message = request('message');
        $message->read_staus = json_encode(array(Auth::user()->id));
        $message->save();
        return request('message');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function chatWithFriend($id)
    {


      $friend_id =  User::whereid($id)->first()->id;
       $data['friendName'] = $id;
       $addFriend_id = AddFriend::orWhere([['request_sender',Auth::user()->id],['request_receiver',$id]])->orWhere([['request_sender',$id],['request_receiver',Auth::user()->id]])->where('request_status','2')->first()->id;
       $readStatusUpdate = Message::where('add_friends_id',$addFriend_id)->select(['id','read_staus'])->get();
       if(!$readStatusUpdate->isEmpty()){
         foreach ($readStatusUpdate as $key => $readStatusUpdates){
           if(is_array(json_decode($readStatusUpdates->read_staus)) && in_array(Auth::user()->id,json_decode($readStatusUpdates->read_staus))){

           }else{
             $readStatus = Message::find($readStatusUpdates->id);
             $readStatus->read_staus = json_encode(array($friend_id,Auth::user()->id));
             $readStatus->save();
           }
         }
       }
       $data['message'] = Message::where('add_friends_id',$addFriend_id)->get();
       return view('chat.message.chat',$data);
    }
}

app/Http/Controllers/InviteFriendsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Mail;
use App\User;
use Auth;

class InviteFriendsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('chat.invite-friends.send-invite');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {


    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
          $email = request('email');
          $authName = Auth::user()->name;
          $chechUser = User::where('email',$email)->first();
          if(!empty($chechUser)){
            return redirect(route('invite-friends.index'))->with('danger','User Already Exists');
          }else{
            $data = [
                    'email'     =>$email,
                    'authName' =>$authName
                  ];
            Mail::send(['html'=>'chat.invite-friends.mail'], ["data"=>$data], function($message) {
                $message->from('kirubharaj555@gmail.com');
                $message->to(request('email'))->subject('Invite From Chat Application');

          });
          return redirect(route('invite-friends.index'))->with('success','Invite Send Successfully');
          }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/chat/invite-friends/mail.blade.php
Your Friend {{ $data['authName']  }} Invited from Chat Application.
Refer this link to chat with your friend : http://localhost:8000/register

resources/views/chat/invite-friends/send-invite.blade.php
@extends('chat.layouts.master')


@section('inner-content')


<div class="content">
<h1 class="content-heading">
Send Invite
</h1>


<div class="block block-rounded block-bordered">
        <div class="block-content">
                     <div class="row">
                       <div class="col-lg-3">
                           <p class="text-muted">

                           </p>
                       </div>
                       <div class="col-lg-8 col-xl-5">
                                    <!-- Form Labels on top - Default Style -->
                                    <form class="mb-5" action="{{ route('invite-friends.store') }}" method="POST" id="form">
                                        {{ csrf_field() }}

                                        <div class="form-group row">
                                            <label for="example-ltf-rate_per_kg" class="col-sm-4 col-form-label" >Enter Friend Email<span class="text-danger">*</span></label>
                                            <div class="col-sm-8">
                                              <input type="email" class="form-control"  id="email" placeholder="Enter Your Friend Email" name="email">
                                           </div>
                                        </div>
                                        <div class="form-group row">
                                          <label for="example-ltf-total_rate" class="col-sm-4 col-form-label" ></label>
                                          <div class="col-sm-8">
                                            <button type="submit" data-toggle="click-ripple" class="btn btn-primary">Send Link</button>
                                            </div>
                                        </div>

                                </div>



                                    </form>
                                    <!-- END Form Labels on top - Default Style -->
                                </div>
                            </div>
                </div>
            </div>

@endsection


@section('javascript')

<script>

$(document).ready(function () {

  $('#form').validate({ // initialize the plugin

      rules: {

        email: {
            required: true,
            email : true
        },
      }
  });

});


</script>
@endsection