routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});


Route::get('/dashboard',function(){
  return view('chat.dashboard');
})->name('dashboard');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Invite Friends
Route::resource('/invite-friends','InviteFriendsController');

//Add Friends
Route::resource('/add-friends','AddFriendsController');
Route::post('/store-request/{id}','AddFriendsController@storeRequest')->name('storeRequest');
Route::get('/request-list','AddFriendsController@requestList')->name('requestList');
Route::post('/request-list/status-update/{id}','AddFriendsController@updateStatus')->name('request.updateStatus');

//chat
Route::resource('/chat','ChatController');
Route::post('/chat/store','ChatController@store');
Route::get('/chat/chat-with-friend/{id}','ChatController@chatWithFriend')->name('chat.chatWithFriend');

app/Message.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    //
}

app/Http/Controllers/ChatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\AddFriend;
use App\Message;
use App\Helper;
use App\User;
class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = AddFriend::where('request_sender',Auth::user()->id)->orwhere('request_receiver',Auth::user()->id)->where('request_status','2')->orderBy('id','desc')->get();
        return view('chat.message.friends-list',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = request('friend_id');
        $addFriend_id = AddFriend::orWhere([['request_sender',Auth::user()->id],['request_receiver',$id]])->orWhere([['request_sender',$id],['request_receiver',Auth::user()->id]])->where('request_status','2')->first()->id;
        $message = new Message();
        $message->add_friends_id = $addFriend_id;
        $message->user_id = Auth::user()->id;
        $message->message = request('message');
        $message->read_staus = json_encode(array(Auth::user()->id));
        $message->save();
        return request('message');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function chatWithFriend($id)
    {


      $friend_id =  User::whereid($id)->first()->id;
       $data['friendName'] = $id;
       $addFriend_id = AddFriend::orWhere([['request_sender',Auth::user()->id],['request_receiver',$id]])->orWhere([['request_sender',$id],['request_receiver',Auth::user()->id]])->where('request_status','2')->first()->id;
       $readStatusUpdate = Message::where('add_friends_id',$addFriend_id)->select(['id','read_staus'])->get();
       if(!$readStatusUpdate->isEmpty()){
         foreach ($readStatusUpdate as $key => $readStatusUpdates){
           if(is_array(json_decode($readStatusUpdates->read_staus)) && in_array(Auth::user()->id,json_decode($readStatusUpdates->read_staus))){

           }else{
             $readStatus = Message::find($readStatusUpdates->id);
             $readStatus->read_staus = json_encode(array($friend_id,Auth::user()->id));
             $readStatus->save();
           }
         }
       }
       $data['message'] = Message::where('add_friends_id',$addFriend_id)->get();
       return view('chat.message.chat',$data);
    }
}

resources/views/chat/message/chat.blade.php
@extends('chat.layouts.master')


@section('inner-content')
<div class="block hero flex-column mb-0 bg-image" style="max-height: 300px;">
                    <!-- Chat #5 Header -->
                    <div class="block-header block-header-default w-100 bg-white-95 shadow-lg" style="min-height: 70px; height: 70px;">
                        <h3 class="block-title">
                            <img class="img-avatar img-avatar32" src="{{ asset('assets/media/avatars/avatar7.jpg') }}" alt="">
                            <span class="font-size-sm font-w600 ml-2">{{ ucfirst(App\Helper::getUserName($friendName)) }}</span>
                        </h3>
                        <div class="block-options">
                            <button type="button" class="btn-block-option">
                                <i class="fa fa-cog"></i>
                            </button>
                            <button type="button" class="btn-block-option d-lg-none" data-toggle="layout" data-action="sidebar_toggle">
                                <i class="fa fa-users"></i>
                            </button>
                        </div>
                    </div>
                    <!-- END Chat #5 Header -->

                    <!-- Chat #5 Messages -->
                    <div class="js-chat-messages block-content block-content-full text-wrap-break-word overflow-y-auto w-100 flex-grow-1 px-lg-8 px-xlg-10 bg-white-90" data-chat-id="5" style="max-height: 350px;">
                      @foreach($message as $messages)
                      @if(Auth::user()->id != $messages->user_id)

                          <div class="mr-4">
                            <div class="d-inline-block font-w600 animated fadeIn bg-body-light border-3x px-3 py-2 mb-2 shadow-sm mw-100 border-left border-dark rounded-right">
                              {{ $messages->message }}
                            </div>
                         </div>
                         <div class=" font-italic text-muted animated fadeIn my-2" style="font-size: x-small;">{{ $messages->created_at->diffForHumans()}}</div>
                      @endif
                      @if(Auth::user()->id == $messages->user_id)

                          <div class="text-right ml-4">
                                <div class="d-inline-block font-w600 animated fadeIn bg-body-light border-3x px-3 py-2 mb-2 shadow-sm mw-100 border-right border-primary rounded-left text-left">
                                  {{ $messages->message }}
                            </div>
                          </div>
                          <div class=" font-italic text-muted animated fadeIn my-2 text-right" style="font-size: x-small;">{{ $messages->created_at->diffForHumans()}}</div>
                    @endif
                       @endforeach
                         <div id="appendMsg"></div>
                    </div>

                    <!-- Chat #5 Input -->
                    <div class="js-chat-form block-content p-3 w-100 d-flex align-items-center bg-white-95 shadow-lg" style="min-height: 70px; height: 70px;">
                        <form class="w-100" action="{{ route('chat.store')  }}" method="POST" id="storemessage">
                          <input type="hidden" value="{{ $friendName }}" name="friend_id">
                            <div class="input-group">

                                <div class="input-group-prepend d-sm-none dropup">
                                    <button type="button" class="btn btn-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="fa fa-plus"></i>
                                    </button>
                                    <div class="dropdown-menu">
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <i class="fa fa-file-alt fa-fw mr-1"></i> Upload File
                                        </a>
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <i class="fa fa-image fa-fw mr-1"></i> Upload Image
                                        </a>
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <i class="fa fa-microphone-alt fa-fw mr-1"></i> Record Audio
                                        </a>
                                        <a class="dropdown-item" href="javascript:void(0)">
                                            <i class="fa fa-smile fa-fw mr-1"></i> Add Stickers
                                        </a>
                                    </div>
                                </div>
                                <div class="input-group-prepend d-none d-sm-flex">

                                </div>
                                <input type="text" name="message" class="js-chat-input form-control form-control-alt border-0 " data-target-chat-id="5" placeholder="Type a message..">
                                <!-- <div class="input-group-append">
                                    <button type="submit" class="btn btn-link">
                                        <i class="fab fa-telegram-plane"></i>
                                        <span class="d-none d-sm-inline ml-1 font-w600">Send</span>
                                    </button>
                                </div> -->
                            </div>
                        </form>
                    </div>
                    <!-- END Chat #5 Input -->
                </div>
@endsection
@section('javascript')
<script>


$(document).ready(function () {
$(".js-chat-messages").animate({ scrollTop: $('.js-chat-messages').prop("scrollHeight")}, 1000);
$('#storemessage').on( 'submit', function(e) {
        e.preventDefault();
        var message = $(this).find('input[name=message]').val();
        var friend_id = $(this).find('input[name=friend_id]').val();
        $.ajax({
            type: "POST",
            url: '/chat/store',
            data: { 'message' : message ,'_token' : "{{ csrf_token() }}" , 'friend_id' : friend_id},
            success: function (message) {
                 //alert(message);

              var msg='<div class="text-right ml-4">'+
                  '<div class="d-inline-block font-w600 animated fadeIn bg-body-light border-3x px-3 py-2 mb-2 shadow-sm mw-100 border-right border-primary rounded-left text-left">'+
                        message
                  '</div>'+
                  '</div>';
                  $('#appendMsg').append(msg);
                  $('input[name=message]').val('');
                  $(".js-chat-messages").animate({ scrollTop: $('.js-chat-messages').prop("scrollHeight")}, 1000);
                  }
        });
        });

  $('#storemessage').validate({ // initialize the plugin
      rules: {
        message : {
          required : true,
        },
      }
  });

});
</script>
@endsection

resources/views/chat/message/chat1.blade.php
@extends('chat.layouts.master')


@section('inner-content')


<div class="content">
<h1 class="content-heading">
Chat With Your Friend
</h1>
<div class="row">
  <div class="col-xl-3">
  </div>
                        <div class="col-xl-6">
                            <!-- Chat #1 -->
                            <div class="block block-rounded">
                                <!-- Chat #1 Header -->
                                <!-- <div class="block-content block-content-full bg-gd-fruit text-center">
                                    <img class="img-avatar img-avatar-thumb" src="{{ asset('assets/media/avatars/avatar10.jpg') }}" alt="">
                                    <p class="font-size-lg font-w600 text-white mt-3 mb-0">
                                        {{ ucfirst(App\Helper::getUserName($friendName)) }}
                                    </p>
                                </div> -->
                                <!-- END Chat #1 Header -->

                                <!-- Chat #1 Messages -->
                                <div class="js-chat-messages block-content block-content-full text-wrap-break-word overflow-y-auto" data-chat-id="1" style="height: 300px;">
                                  @foreach($message as $messages)
                                  @if(Auth::user()->id != $messages->user_id)

                                      <div class="mr-4">
                                        <div class="d-inline-block font-w600 animated fadeIn bg-body-light border-3x px-3 py-2 mb-2 shadow-sm mw-100 border-left border-dark rounded-right">
                                          {{ $messages->message }}
                                        </div>
                                     </div>
                                     <div class=" font-italic text-muted animated fadeIn my-2" style="font-size: x-small;">{{ $messages->created_at->diffForHumans()}}</div>
                                  @endif
                                  @if(Auth::user()->id == $messages->user_id)

                                      <div class="text-right ml-4">
                                            <div class="d-inline-block font-w600 animated fadeIn bg-body-light border-3x px-3 py-2 mb-2 shadow-sm mw-100 border-right border-primary rounded-left text-left">
                                              {{ $messages->message }}
                                        </div>
                                      </div>
                                      <div class=" font-italic text-muted animated fadeIn my-2 text-right" style="font-size: x-small;">{{ $messages->created_at->diffForHumans()}}</div>
                                @endif
                                   @endforeach
                                     <div id="appendMsg"></div>
                                </div>

                                <!-- Chat #1 Input -->
                                <div class="js-chat-form block-content p-2 bg-body-dark">
                                    <form action="{{ route('chat.store')  }}" method="POST" id="storemessage">
                                        <input type="text" name="message" class="js-chat-input form-control form-control-alt" data-target-chat-id="1" placeholder="Type a message..">
                                        <input type="hidden" value="{{ $friendName }}" name="friend_id">
                                    </form>
                                </div>
                                <!-- END Chat #1 Input -->
                            </div>
                            <!-- END Chat #1 -->
                        </div>
                    </div>
                    <div class="col-xl-3">
                    </div>
</div>
@endsection
@section('javascript')
<script>


$(document).ready(function () {
$(".js-chat-messages").animate({ scrollTop: $('.js-chat-messages').prop("scrollHeight")}, 1000);
$('#storemessage').on( 'submit', function(e) {
        e.preventDefault();
        var message = $(this).find('input[name=message]').val();
        var friend_id = $(this).find('input[name=friend_id]').val();
        $.ajax({
            type: "POST",
            url: '/chat/store',
            data: { 'message' : message ,'_token' : "{{ csrf_token() }}" , 'friend_id' : friend_id},
            success: function (message) {
                 //alert(message);

              var msg='<div class="text-right ml-4">'+
                  '<div class="d-inline-block font-w600 animated fadeIn bg-body-light border-3x px-3 py-2 mb-2 shadow-sm mw-100 border-right border-primary rounded-left text-left">'+
                        message
                  '</div>'+
                  '</div>';
                  $('#appendMsg').append(msg);
                  $('input[name=message]').val('');
                  $(".js-chat-messages").animate({ scrollTop: $('.js-chat-messages').prop("scrollHeight")}, 1000);
                  }
        });
        });

  $('#storemessage').validate({ // initialize the plugin
      rules: {
        message : {
          required : true,
        },
      }
  });

});
</script>
@endsection

resources/views/chat/message/friends-list.blade.php
@extends('chat.layouts.master')


@section('inner-content')


<div class="content">
<h1 class="content-heading">
Friends List
</h1>



                     <div class="row">
                      @foreach($data as $datas)
                       <div class="col-md-6 col-xl-3">
                          @if($datas->request_sender == Auth::user()->id)
                             <a class="block block-rounded block-link-pop" href="{{ route('chat.chatWithFriend',$datas->request_receiver) }}" target="_blank">
                                 <div class="block-content block-content-full d-flex align-items-center justify-content-between">
                                     <img class="img-avatar img-avatar48" src="assets/media/avatars/avatar9.jpg" alt="">
                                     <div class="ml-3 text-right">
                                         <p class="font-w600 mb-0">{{ ucfirst(App\Helper::getSenderName($datas->request_receiver))  }}</p>
                                         <p class="font-size-sm font-italic text-muted mb-0">
                                             @php($newMessage = App\Helper::getNewMessages($datas->id))
                                             @if($newMessage == 1)
                                                  <span class="badge badge-warning">No New Message</span>
                                             @elseif($newMessage == 2)
                                                  <span class="badge badge-success">New Message</span>
                                             @elseif($newMessage == 3)
                                                  <span class="badge badge-warning">No New Message</span>
                                             @endif

                                         </p>
                                     </div>
                                 </div>
                             </a>
                             @endif
                             @if($datas->request_receiver == Auth::user()->id)
                                <a class="block block-rounded block-link-pop" href="{{ route('chat.chatWithFriend',$datas->request_sender) }}" target="_blank">
                                    <div class="block-content block-content-full d-flex align-items-center justify-content-between">
                                        <img class="img-avatar img-avatar48" src="assets/media/avatars/avatar9.jpg" alt="">
                                        <div class="ml-3 text-right">
                                            <p class="font-w600 mb-0">{{ ucfirst(App\Helper::getSenderName($datas->request_sender))  }}</p>
                                            <p class="font-size-sm font-italic text-muted mb-0">
                                            @php($newMessage = App\Helper::getNewMessages($datas->id))
                                            @if($newMessage == 1)
                                                 <span class="badge badge-warning">No New Message</span>
                                            @elseif($newMessage == 2)
                                                 <span class="badge badge-success">New Message</span>
                                            @elseif($newMessage == 3)
                                                 <span class="badge badge-warning">No New Message</span>
                                            @endif
                                            </p>
                                        </div>
                                    </div>
                                </a>
                                @endif
                          </div>
                      @endforeach
                      </div>
@endsection